# Use an official Python runtime as a parent image
FROM python:3.9-slim
 
# Set the working directory in the container
WORKDIR /app
 
# Copy the current directory contents into the container at /app
COPY . /app/
 
# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt
 
# Expose the port the app runs on
EXPOSE 8000
 
# Define environment variable
ENV PYTHONUNBUFFERED 1
 
# Run the application
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
